# Time Travel Query Demonstration

In [1]:
#Imports
from deltalake import DeltaTable
import json
import pandas as pd

In [2]:
#Connection Credentials
STORAGE_OPTIONS = {
    "endpoint_url": "http://localhost:9000",
    "aws_access_key_id": "minioadmin",
    "aws_secret_access_key": "minioadmin",
    "aws_region": "us-east-1",
    "allow_http": "true",
}

## Taxi Demonstration

### Version History

We first get the available layers for time travel queries, gold has seperate folders so we break down each folder into one

In [3]:
layers = {
    "Bronze": "s3://bronze/taxi/",
    "Silver": "s3://silver/taxi/",
    
    #Gold Layer Folders
    "Gold_Daily_Summary":   "s3://gold/taxi/daily_summary/",
    "Gold_Hourly_Summary":   "s3://gold/taxi/hourly_summary/",
    "Gold_Individual_Day_Summary":   "s3://gold/taxi/individual_day_summary/",
    "Gold_Payment_Summary":   "s3://gold/taxi/payment_summary/",
    "Gold_Zone_Performance":   "s3://gold/taxi/zone_performance/",
}

For each layer we get the version history available from the logs (Last 5)

In [4]:
print("Getting version histories for each layer")

for name, uri in layers.items():
    dt = DeltaTable(uri, storage_options=STORAGE_OPTIONS)
    history = dt.history(5)
    
    print(f"\n=== {name} — {len(dt.history())} versions ===")
    df = pd.DataFrame(history)[["version", "timestamp", "operation"]]

    display(df)

    print("Details of Last Operation: ")
    print(json.dumps(history[0], indent=2, default=str))

Getting version histories for each layer

=== Bronze — 51 versions ===

   version      timestamp operation
0       50  1777351176694     WRITE
1       49  1777351003496     WRITE
2       48  1777350843262     WRITE
3       47  1777350683794     WRITE
4       46  1777350547232     WRITE

Details of Last Operation:
{
  "timestamp": 1777351176694,
  "operation": "WRITE",
  "operationParameters": {
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite",
    "predicate": "source_year = 2021 AND source_month = 6"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 6310,
    "num_added_files": 1,
    "num_added_rows": 2834264,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "version": 50
}

=== Silver — 30 versions ===

   version      timestamp operation
0       29  1777351215308     WRITE
1       28  1777351048674     WRITE
2       27  1777350886241     WRITE
3       26  1777350721839     WRITE
4       25  1777350581673     WRITE

Details of Last Operation:
{
  "timestamp": 1777351215308,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2021 AND source_month = 6",
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 8919,
    "num_added_files": 1,
    "num_added_rows": 2614933,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "version": 29
}

=== Gold_Daily_Summary — 18 versions ===

   version      timestamp operation
0       17  1777351286163     WRITE
1       16  1777351139874     WRITE
2       15  1777350971256     WRITE
3       14  1777350813366     WRITE
4       13  1777350654063     WRITE

Details of Last Operation:
{
  "timestamp": 1777351286163,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2021 AND source_month = 6",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 83,
    "num_added_files": 1,
    "num_added_rows": 7,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 17
}

=== Gold_Hourly_Summary — 18 versions ===

   version      timestamp operation
0       17  1777351289428     WRITE
1       16  1777351144668     WRITE
2       15  1777350975950     WRITE
3       14  1777350818245     WRITE
4       13  1777350658739     WRITE

Details of Last Operation:
{
  "timestamp": 1777351289428,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2021 AND source_month = 6",
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 72,
    "num_added_files": 1,
    "num_added_rows": 24,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 17
}

=== Gold_Individual_Day_Summary — 18 versions ===

   version      timestamp operation
0       17  1777351288180     WRITE
1       16  1777351143175     WRITE
2       15  1777350974495     WRITE
3       14  1777350816402     WRITE
4       13  1777350656987     WRITE

Details of Last Operation:
{
  "timestamp": 1777351288180,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2021 AND source_month = 6",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 69,
    "num_added_files": 1,
    "num_added_rows": 30,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "version": 17
}

=== Gold_Payment_Summary — 12 versions ===

   version      timestamp operation
0       11  1777351290271     WRITE
1       10  1777351145957     WRITE
2        9  1777350977204     WRITE
3        8  1777350819522     WRITE
4        7  1777350659951     WRITE

Details of Last Operation:
{
  "timestamp": 1777351290271,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2021 AND source_month = 6",
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 76,
    "num_added_files": 1,
    "num_added_rows": 4,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "version": 11
}

=== Gold_Zone_Performance — 18 versions ===

   version      timestamp operation
0       17  1777351287177     WRITE
1       16  1777351141671     WRITE
2       15  1777350973051     WRITE
3       14  1777350814980     WRITE
4       13  1777350655634     WRITE

Details of Last Operation:
{
  "timestamp": 1777351287177,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2021 AND source_month = 6",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 193,
    "num_added_files": 1,
    "num_added_rows": 21591,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "version": 17
}

#### Bronze Time Travel

We check what the bronze table looked like after the first 5 tables were loaded.

A predicate indicates the file for that predicate was overwritten at that version.

In [5]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Bronze"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 02:42:34
  Predicate : N/A
  Row count : 2,824,209
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("long"), trip_distance: PrimitiveType("double"), RatecodeID: PrimitiveType("long"), store_and_fwd_flag: PrimitiveType("string"), PULocationID: PrimitiveType("integer"), DOLocationID: PrimitiveType("integer"), payment_type: PrimitiveType("long"), fare_amount: PrimitiveType("double"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 02:42:34
  Predicate : N/A
  Row count : 6,112,459
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("long"), trip_distance: PrimitiveType("double"), RatecodeID: PrimitiveType("long"), store_and_fwd_flag: PrimitiveType("string"), PULocationID: PrimitiveType("integer"), DOLocationID: PrimitiveType("integer"), payment_type: PrimitiveType("long"), fare_amount: PrimitiveType("double"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 02:42:36
  Predicate : N/A
  Row count : 9,026,414
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("long"), trip_distance: PrimitiveType("double"), RatecodeID: PrimitiveType("long"), store_and_fwd_flag: PrimitiveType("string"), PULocationID: PrimitiveType("integer"), DOLocationID: PrimitiveType("integer"), payment_type: PrimitiveType("long"), fare_amount: PrimitiveType("double"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 02:42:41
  Predicate : N/A
  Row count : 12,430,180
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("long"), trip_distance: PrimitiveType("double"), RatecodeID: PrimitiveType("long"), store_and_fwd_flag: PrimitiveType("string"), PULocationID: PrimitiveType("integer"), DOLocationID: PrimitiveType("integer"), payment_type: PrimitiveType("long"), fare_amount: PrimitiveType("double"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 4
  Ingested  : April 27, 2026 02:43:45
  Predicate : source_year = 2023 AND source_month = 5
  Row count : 15,943,829
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("long"), trip_distance: PrimitiveType("double"), RatecodeID: PrimitiveType("long"), store_and_fwd_flag: PrimitiveType("string"), PULocationID: PrimitiveType("integer"), DOLocationID: PrimitiveType("integer"), payment_type: PrimitiveType("long"), fare_amount: PrimitiveType("double"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────

In production, Ingested At will show the actual month and year ingested since the pipeline will only run once per month

### Silver Time Travel

Check what silver looks like after each transform is done

In [6]:
dt = DeltaTable(layers["Silver"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Silver"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 02:47:01
  Predicate : N/A
  Row count : 2,644,206
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 02:47:01
  Predicate : N/A
  Row count : 5,391,219
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 02:49:06
  Predicate : source_year = 2023 AND source_month = 11
  Row count : 8,497,353
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 02:54:15
  Predicate : source_year = 2023 AND source_month = 12
  Row count : 11,587,954
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 4
  Ingested  : April 27, 2026 02:56:44
  Predicate : source_year = 2023 AND source_month = 3
  Row count : 14,794,212
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────

In production this can be done using different months and timestamps for when the transform was executed in airflow

#### Schema Evolution At Bronze Layer

We check to see which columns were removed or added over time

In [7]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)

# Build a schema snapshot for each of the first 5 versions
version_schemas = {}
for version in range(0, 5):
    dt_v = DeltaTable(layers["Bronze"], version=version, storage_options=STORAGE_OPTIONS)
    version_schemas[version] = {field.name: str(field.type) for field in dt_v.schema().fields}

# Use version 0 as the baseline
baseline = version_schemas[0]
baseline_cols = set(baseline.keys())

print(f"{'─' * 60}")
print(f"  Baseline schema (version 0) — {len(baseline_cols)} columns")
for name, dtype in baseline.items():
    print(f"    {name}: {dtype}")

for version in range(1, 5):
    current_cols = set(version_schemas[version].keys())
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")

    added   = current_cols - baseline_cols
    removed = baseline_cols - current_cols
    changed = {
        col for col in current_cols & baseline_cols
        if version_schemas[version][col] != baseline[col]
    }

    print(f"{'─' * 60}")
    print(f"  Version {version} | {ts}")

    if not added and not removed and not changed:
        print(f"    No schema changes from version 0")
    if added:
        for col in added:
            print(f"    + ADDED   {col}: {version_schemas[version][col]}")
    if removed:
        for col in removed:
            print(f"    - REMOVED {col}: {baseline[col]}")
    if changed:
        for col in changed:
            print(f"    ~ CHANGED {col}: {baseline[col]} -> {version_schemas[version][col]}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Baseline schema (version 0) — 23 columns
    VendorID: PrimitiveType("integer")
    tpep_pickup_datetime: PrimitiveType("timestamp_ntz")
    tpep_dropoff_datetime: PrimitiveType("timestamp_ntz")
    passenger_count: PrimitiveType("long")
    trip_distance: PrimitiveType("double")
    RatecodeID: PrimitiveType("long")
    store_and_fwd_flag: PrimitiveType("string")
    PULocationID: PrimitiveType("integer")
    DOLocationID: PrimitiveType("integer")
    payment_type: PrimitiveType("long")
    fare_amount: PrimitiveType("double")
    extra: PrimitiveType("double")
    mta_tax: PrimitiveType("double")
    tip_amount: PrimitiveType("double")
    tolls_amount: PrimitiveType("double")
    improvement_surcharge: PrimitiveType("double")
    total_amount: PrimitiveType("double")
    congestion_surcharge: PrimitiveType("double")
    Airport_fee: PrimitiveType("double")
    ingested_at: PrimitiveType("timestamp")
    source_file: PrimitiveType("string")
    source_year: PrimitiveType("short")
    source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version 1 | April 27, 2026 02:47:01
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 2 | April 27, 2026 02:49:06
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 3 | April 27, 2026 02:54:15
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 4 | April 27, 2026 02:56:44
    No schema changes from version 0
────────────────────────────────────────────────────────────

## Weather Demonstration

### Version History

We first get the available layers for time travel queries, gold has seperate folders so we break down each folder into one

In [8]:
layers = {
    "Bronze": "s3://bronze/weather/",
    "Silver": "s3://silver/weather/",
    
    #Gold Layer Folders
    "Gold_Daily_Climate":   "s3://gold/weather/daily_climate/",
    "Gold_Monthly_Climate":   "s3://gold/weather/monthly_climate/",
    "Gold_Station_Metrics":   "s3://gold/weather/station_metrics/"
}

For each layer we get the version history available from the logs (Last 5)

In [9]:
print("Getting version histories for each layer")

for name, uri in layers.items():
    dt = DeltaTable(uri, storage_options=STORAGE_OPTIONS)
    history = dt.history(5)
    
    print(f"\n=== {name} — {len(dt.history())} versions ===")
    df = pd.DataFrame(history)[["version", "timestamp", "operation"]]

    display(df)

    print("Details of Last Operation: ")
    print(json.dumps(history[0], indent=2, default=str))

Getting version histories for each layer

=== Bronze — 10 versions ===

   version      timestamp operation
0        9  1777355057236     WRITE
1        8  1777353988574     WRITE
2        7  1777353759700     WRITE
3        6  1777353506232     WRITE
4        5  1777353261562     WRITE

Details of Last Operation:
{
  "timestamp": 1777355057236,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023",
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 5446,
    "num_added_files": 12,
    "num_added_rows": 4038747,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "version": 9
}

=== Silver — 10 versions ===

   version      timestamp operation
0        9  1777355124073     WRITE
1        8  1777354017659     WRITE
2        7  1777353791330     WRITE
3        6  1777353543817     WRITE
4        5  1777353291965     WRITE

Details of Last Operation:
{
  "timestamp": 1777355124073,
  "operation": "WRITE",
  "operationParameters": {
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite",
    "predicate": "source_year = 2023"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 3675,
    "num_added_files": 12,
    "num_added_rows": 2081063,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "version": 9
}

=== Gold_Daily_Climate — 10 versions ===

   version      timestamp operation
0        9  1777355300539     WRITE
1        8  1777354090017     WRITE
2        7  1777353865242     WRITE
3        6  1777353629830     WRITE
4        5  1777353396970     WRITE

Details of Last Operation:
{
  "timestamp": 1777355300539,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 3951,
    "num_added_files": 12,
    "num_added_rows": 4162126,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "version": 9
}

=== Gold_Monthly_Climate — 10 versions ===

   version      timestamp operation
0        9  1777355301858     WRITE
1        8  1777354090900     WRITE
2        7  1777353866277     WRITE
3        6  1777353630732     WRITE
4        5  1777353398364     WRITE

Details of Last Operation:
{
  "timestamp": 1777355301858,
  "operation": "WRITE",
  "operationParameters": {
    "mode": "Overwrite",
    "predicate": "source_year = 2023",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 345,
    "num_added_files": 12,
    "num_added_rows": 83510,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 9
}

=== Gold_Station_Metrics — 10 versions ===

   version      timestamp operation
0        9  1777355302929     WRITE
1        8  1777354091766     WRITE
2        7  1777353867130     WRITE
3        6  1777353631528     WRITE
4        5  1777353399543     WRITE

Details of Last Operation:
{
  "timestamp": 1777355302929,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 331,
    "num_added_files": 12,
    "num_added_rows": 83510,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "version": 9
}

### Bronze Time Travel

We check what the bronze table looked like after the first 5 tables were loaded.

A predicate indicates the file for that predicate was overwritten at that version.

In [10]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Bronze"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 05:22:03
  Predicate : N/A
  Row count : 4,119,205
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 05:33:07
  Predicate : source_year = 2022
  Row count : 8,113,904
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 05:33:11
  Predicate : source_year = 2021
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 05:51:29
  Predicate : source_year = 2021
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 4
  Ingested  : April 28, 2026 05:10:14
  Predicate : source_year = 2020
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────

In production, Ingested At will show the actual month and year ingested since the pipeline will only run once per month

### Silver Time Travel

Check what silver looks like after each transform is done

In [11]:
dt = DeltaTable(layers["Silver"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Silver"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 05:23:07
  Predicate : N/A
  Row count : 2,077,130
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 05:34:47
  Predicate : source_year = 2021
  Row count : 4,152,894
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 05:34:47
  Predicate : source_year = 2022
  Row count : 6,238,193
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 05:52:06
  Predicate : source_year = 2021
  Row count : 6,238,193
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 4
  Ingested  : April 28, 2026 05:10:53
  Predicate : source_year = 2020
  Row count : 6,238,193
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────

In production this can be done using different months and timestamps for when the transform was executed in airflow

#### Schema Evolution At Bronze Layer

We check to see which columns were removed or added over time

In [12]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)

# Build a schema snapshot for each of the first 5 versions
version_schemas = {}
for version in range(0, 5):
    dt_v = DeltaTable(layers["Bronze"], version=version, storage_options=STORAGE_OPTIONS)
    version_schemas[version] = {field.name: str(field.type) for field in dt_v.schema().fields}

# Use version 0 as the baseline
baseline = version_schemas[0]
baseline_cols = set(baseline.keys())

print(f"{'─' * 60}")
print(f"  Baseline schema (version 0) — {len(baseline_cols)} columns")
for name, dtype in baseline.items():
    print(f"    {name}: {dtype}")

for version in range(1, 5):
    current_cols = set(version_schemas[version].keys())
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")

    added   = current_cols - baseline_cols
    removed = baseline_cols - current_cols
    changed = {
        col for col in current_cols & baseline_cols
        if version_schemas[version][col] != baseline[col]
    }

    print(f"{'─' * 60}")
    print(f"  Version {version} | {ts}")

    if not added and not removed and not changed:
        print(f"    No schema changes from version 0")
    if added:
        for col in added:
            print(f"    + ADDED   {col}: {version_schemas[version][col]}")
    if removed:
        for col in removed:
            print(f"    - REMOVED {col}: {baseline[col]}")
    if changed:
        for col in changed:
            print(f"    ~ CHANGED {col}: {baseline[col]} -> {version_schemas[version][col]}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Baseline schema (version 0) — 32 columns
    STATION: PrimitiveType("string")
    DATE: PrimitiveType("date")
    LATITUDE: PrimitiveType("double")
    LONGITUDE: PrimitiveType("double")
    ELEVATION: PrimitiveType("double")
    NAME: PrimitiveType("string")
    TEMP: PrimitiveType("double")
    TEMP_ATTRIBUTES: PrimitiveType("long")
    DEWP: PrimitiveType("double")
    DEWP_ATTRIBUTES: PrimitiveType("long")
    SLP: PrimitiveType("double")
    SLP_ATTRIBUTES: PrimitiveType("long")
    STP: PrimitiveType("double")
    STP_ATTRIBUTES: PrimitiveType("long")
    VISIB: PrimitiveType("double")
    VISIB_ATTRIBUTES: PrimitiveType("long")
    WDSP: PrimitiveType("double")
    WDSP_ATTRIBUTES: PrimitiveType("long")
    MXSPD: PrimitiveType("double")
    GUST: PrimitiveType("double")
    MAX: PrimitiveType("double")
    MAX_ATTRIBUTES: PrimitiveType("string")
    MIN: PrimitiveType("double")
    MIN_ATTRIBUTES: PrimitiveType("string")
    PRCP: PrimitiveType("double")
    PRCP_ATTRIBUTES: PrimitiveType("string")
    SNDP: PrimitiveType("double")
    FRSHTT: PrimitiveType("long")
    ingested_at: PrimitiveType("timestamp")
    source_file: PrimitiveType("string")
    source_year: PrimitiveType("short")
    source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version 1 | April 27, 2026 05:34:47
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 2 | April 27, 2026 05:34:47
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 3 | April 27, 2026 05:52:06
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 4 | April 28, 2026 05:10:53
    No schema changes from version 0
────────────────────────────────────────────────────────────