# Time Travel Query Demonstration

In [2]:
#Imports
from deltalake import DeltaTable
import json
import pandas as pd

In [3]:
#Connection Credentials
STORAGE_OPTIONS = {
    "endpoint_url": "http://localhost:9000",
    "aws_access_key_id": "minioadmin",
    "aws_secret_access_key": "minioadmin",
    "aws_region": "us-east-1",
    "allow_http": "true",
}

## Taxi Demonstration

### Version History

We first get the available layers for time travel queries, gold has seperate folders so we break down each folder into one

In [4]:
layers = {
    "Bronze": "s3://bronze/taxi/",
    "Silver": "s3://silver/taxi/",
    
    #Gold Layer Folders
    "Gold_Borough_Summary":   "s3://gold/taxi/borough_summary/",
    "Gold_Daily_Summary":   "s3://gold/taxi/daily_summary/",
    "Gold_Hourly_Summary":   "s3://gold/taxi/hourly_summary/",
    "Gold_Individual_Day_Summary":   "s3://gold/taxi/individual_day_summary/",
    "Gold_Payment_Summary":   "s3://gold/taxi/payment_summary/",
    "Gold_Zone_Performance":   "s3://gold/taxi/zone_performance/",
}

For each layer we get the version history available from the logs (Last 5)

In [5]:
print("Getting version histories for each layer")

for name, uri in layers.items():
    dt = DeltaTable(uri, storage_options=STORAGE_OPTIONS)
    history = dt.history(5)
    
    print(f"\n=== {name} — {len(dt.history())} versions ===")
    df = pd.DataFrame(history)[["version", "timestamp", "operation"]]

    display(df)

    print("Details of Last Operation: ")
    print(json.dumps(history[0], indent=2, default=str))

Getting version histories for each layer

=== Bronze — 24 versions ===

   version      timestamp operation
0       23  1777261029845     WRITE
1       22  1777261020285     WRITE
2       21  1777261002750     WRITE
3       20  1777260986224     WRITE
4       19  1777260974416     WRITE

Details of Last Operation:
{
  "timestamp": 1777261029845,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023 AND source_month = 12",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 4194,
    "num_added_files": 1,
    "num_added_rows": 3376567,
    "num_partitions": 0,
    "num_removed_files": 1
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 23
}

=== Silver — 22 versions ===

   version      timestamp operation
0       21  1777261419253     WRITE
1       20  1777261403497     WRITE
2       19  1777261386390     WRITE
3       18  1777261364474     WRITE
4       17  1777261340911     WRITE

Details of Last Operation:
{
  "timestamp": 1777261419253,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023 AND source_month = 12",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 8151,
    "num_added_files": 1,
    "num_added_rows": 3090601,
    "num_partitions": 0,
    "num_removed_files": 1
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 21
}

=== Gold_Borough_Summary — 2 versions ===

   version      timestamp operation
0        1  1777265843626     WRITE
1        0  1777265731396     WRITE

Details of Last Operation:
{
  "timestamp": 1777265843626,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023 AND source_month = 2",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 231,
    "num_added_files": 1,
    "num_added_rows": 21482,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 1
}

=== Gold_Daily_Summary — 8 versions ===

   version      timestamp operation
0        7  1777265837895     WRITE
1        6  1777265725200     WRITE
2        5  1777265436141     WRITE
3        4  1777263754858     WRITE
4        3  1777263724841     WRITE

Details of Last Operation:
{
  "timestamp": 1777265837895,
  "operation": "WRITE",
  "operationParameters": {
    "mode": "Overwrite",
    "predicate": "source_year = 2023 AND source_month = 2",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 216,
    "num_added_files": 1,
    "num_added_rows": 7,
    "num_partitions": 0,
    "num_removed_files": 1
  },
  "version": 7
}

=== Gold_Hourly_Summary — 8 versions ===

   version      timestamp operation
0        7  1777265841312     WRITE
1        6  1777265730123     WRITE
2        5  1777265444168     WRITE
3        4  1777263757407     WRITE
4        3  1777263726525     WRITE

Details of Last Operation:
{
  "timestamp": 1777265841312,
  "operation": "WRITE",
  "operationParameters": {
    "mode": "Overwrite",
    "predicate": "source_year = 2023 AND source_month = 2",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 136,
    "num_added_files": 1,
    "num_added_rows": 24,
    "num_partitions": 0,
    "num_removed_files": 1
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 7
}

=== Gold_Individual_Day_Summary — 8 versions ===

   version      timestamp operation
0        7  1777265840211     WRITE
1        6  1777265728869     WRITE
2        5  1777265441002     WRITE
3        4  1777263756697     WRITE
4        3  1777263726060     WRITE

Details of Last Operation:
{
  "timestamp": 1777265840211,
  "operation": "WRITE",
  "operationParameters": {
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "predicate": "source_year = 2023 AND source_month = 2"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 118,
    "num_added_files": 1,
    "num_added_rows": 28,
    "num_partitions": 0,
    "num_removed_files": 1
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 7
}

=== Gold_Payment_Summary — 2 versions ===

   version      timestamp operation
0        1  1777265842762     WRITE
1        0  1777265730774     WRITE

Details of Last Operation:
{
  "timestamp": 1777265842762,
  "operation": "WRITE",
  "operationParameters": {
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite",
    "predicate": "source_year = 2023 AND source_month = 2"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 258,
    "num_added_files": 1,
    "num_added_rows": 4,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 1
}

=== Gold_Zone_Performance — 8 versions ===

   version      timestamp operation
0        7  1777265839234     WRITE
1        6  1777265727999     WRITE
2        5  1777265438077     WRITE
3        4  1777263755909     WRITE
4        3  1777263725605     WRITE

Details of Last Operation:
{
  "timestamp": 1777265839234,
  "operation": "WRITE",
  "operationParameters": {
    "predicate": "source_year = 2023 AND source_month = 2",
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 283,
    "num_added_files": 1,
    "num_added_rows": 21482,
    "num_partitions": 0,
    "num_removed_files": 1
  },
  "version": 7
}

#### Bronze Time Travel

We check what the bronze table looked like after the first 5 tables were loaded.

A predicate indicates the file for that predicate was overwritten at that version.

In [13]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Bronze"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 05:22:03
  Predicate : N/A
  Row count : 4,119,205
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 05:33:07
  Predicate : source_year = 2022
  Row count : 8,113,904
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 05:33:11
  Predicate : source_year = 2021
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 05:51:29
  Predicate : source_year = 2021
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")

DeltaError: Kernel error: Generic delta kernel error: LogSegment end version 3 not the same as the specified end version 4

In production, Ingested At will show the actual month and year ingested since the pipeline will only run once per month

### Silver Time Travel

Check what silver looks like after each transform is done

In [7]:
dt = DeltaTable(layers["Silver"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Silver"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 02:47:01
  Predicate : N/A
  Row count : 2,644,206
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 02:47:01
  Predicate : N/A
  Row count : 5,391,219
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 02:49:06
  Predicate : source_year = 2023 AND source_month = 11
  Row count : 8,497,353
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 02:54:15
  Predicate : source_year = 2023 AND source_month = 12
  Row count : 11,587,954
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────
  Version   : 4
  Ingested  : April 27, 2026 02:56:44
  Predicate : source_year = 2023 AND source_month = 3
  Row count : 14,794,212
  Schema    : VendorID: PrimitiveType("integer"), tpep_pickup_datetime: PrimitiveType("timestamp_ntz"), tpep_dropoff_datetime: PrimitiveType("timestamp_ntz"), passenger_count: PrimitiveType("byte"), trip_distance: PrimitiveType("float"), PULocationID: PrimitiveType("short"), DOLocationID: PrimitiveType("short"), payment_type: PrimitiveType("byte"), fare_amount: PrimitiveType("float"), extra: PrimitiveType("double"), mta_tax: PrimitiveType("double"), tip_amount: PrimitiveType("double"), tolls_amount: PrimitiveType("double"), improvement_surcharge: PrimitiveType("double"), total_amount: PrimitiveType("double"), congestion_surcharge: PrimitiveType("double"), Airport_fee: PrimitiveType("double"), store_and_fwd_flag: PrimitiveType("string"), RatecodeID: PrimitiveType("long"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), trip_duration_minutes: PrimitiveType("long"), pickup_day_of_week: PrimitiveType("byte"), trip_speed_mph: PrimitiveType("float"), pickup_hour: PrimitiveType("byte"), processed_at: PrimitiveType("timestamp"), payment_method: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), pickup_date: PrimitiveType("date")
────────────────────────────────────────────────────────────

In production this can be done using different months and timestamps for when the transform was executed in airflow

#### Schema Evolution At Bronze Layer

We check to see which columns were removed or added over time

In [8]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)

# Build a schema snapshot for each of the first 5 versions
version_schemas = {}
for version in range(0, 5):
    dt_v = DeltaTable(layers["Bronze"], version=version, storage_options=STORAGE_OPTIONS)
    version_schemas[version] = {field.name: str(field.type) for field in dt_v.schema().fields}

# Use version 0 as the baseline
baseline = version_schemas[0]
baseline_cols = set(baseline.keys())

print(f"{'─' * 60}")
print(f"  Baseline schema (version 0) — {len(baseline_cols)} columns")
for name, dtype in baseline.items():
    print(f"    {name}: {dtype}")

for version in range(1, 5):
    current_cols = set(version_schemas[version].keys())
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")

    added   = current_cols - baseline_cols
    removed = baseline_cols - current_cols
    changed = {
        col for col in current_cols & baseline_cols
        if version_schemas[version][col] != baseline[col]
    }

    print(f"{'─' * 60}")
    print(f"  Version {version} | {ts}")

    if not added and not removed and not changed:
        print(f"    No schema changes from version 0")
    if added:
        for col in added:
            print(f"    + ADDED   {col}: {version_schemas[version][col]}")
    if removed:
        for col in removed:
            print(f"    - REMOVED {col}: {baseline[col]}")
    if changed:
        for col in changed:
            print(f"    ~ CHANGED {col}: {baseline[col]} -> {version_schemas[version][col]}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Baseline schema (version 0) — 23 columns
    VendorID: PrimitiveType("integer")
    tpep_pickup_datetime: PrimitiveType("timestamp_ntz")
    tpep_dropoff_datetime: PrimitiveType("timestamp_ntz")
    passenger_count: PrimitiveType("long")
    trip_distance: PrimitiveType("double")
    RatecodeID: PrimitiveType("long")
    store_and_fwd_flag: PrimitiveType("string")
    PULocationID: PrimitiveType("integer")
    DOLocationID: PrimitiveType("integer")
    payment_type: PrimitiveType("long")
    fare_amount: PrimitiveType("double")
    extra: PrimitiveType("double")
    mta_tax: PrimitiveType("double")
    tip_amount: PrimitiveType("double")
    tolls_amount: PrimitiveType("double")
    improvement_surcharge: PrimitiveType("double")
    total_amount: PrimitiveType("double")
    congestion_surcharge: PrimitiveType("double")
    Airport_fee: PrimitiveType("double")
    ingested_at: PrimitiveType("timestamp")
    source_file: PrimitiveType("string")
    source_year: PrimitiveType("short")
    source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version 1 | April 27, 2026 02:47:01
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 2 | April 27, 2026 02:49:06
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 3 | April 27, 2026 02:54:15
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 4 | April 27, 2026 02:56:44
    No schema changes from version 0
────────────────────────────────────────────────────────────

## Weather Demonstration

### Version History

We first get the available layers for time travel queries, gold has seperate folders so we break down each folder into one

In [11]:
layers = {
    "Bronze": "s3://bronze/weather/",
    "Silver": "s3://silver/weather/",
    
    #Gold Layer Folders
    "Gold_Daily_Climate":   "s3://gold/weather/daily_climate/",
    "Gold_Monthly_Climate":   "s3://gold/weather/monthly_climate/",
    "Gold_Station_Metrics":   "s3://gold/weather/station_metrics/"
}

For each layer we get the version history available from the logs (Last 5)

In [12]:
print("Getting version histories for each layer")

for name, uri in layers.items():
    dt = DeltaTable(uri, storage_options=STORAGE_OPTIONS)
    history = dt.history(5)
    
    print(f"\n=== {name} — {len(dt.history())} versions ===")
    df = pd.DataFrame(history)[["version", "timestamp", "operation"]]

    display(df)

    print("Details of Last Operation: ")
    print(json.dumps(history[0], indent=2, default=str))

Getting version histories for each layer

=== Bronze — 4 versions ===

   version      timestamp operation
0        3  1777269089772     WRITE
1        2  1777267991149     WRITE
2        1  1777267987967     WRITE
3        0  1777267323362     WRITE

Details of Last Operation:
{
  "timestamp": 1777269089772,
  "operation": "WRITE",
  "operationParameters": {
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite",
    "predicate": "source_year = 2021"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 4824,
    "num_added_files": 12,
    "num_added_rows": 4026550,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "version": 3
}

=== Silver — 4 versions ===

   version      timestamp operation
0        3  1777269126694     WRITE
1        2  1777268087472     WRITE
2        1  1777268087276     WRITE
3        0  1777267387481     WRITE

Details of Last Operation:
{
  "timestamp": 1777269126694,
  "operation": "WRITE",
  "operationParameters": {
    "mode": "Overwrite",
    "predicate": "source_year = 2021",
    "partitionBy": "[\"source_year\",\"source_month\"]"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 2720,
    "num_added_files": 12,
    "num_added_rows": 2075764,
    "num_partitions": 0,
    "num_removed_files": 12
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 3
}

=== Gold_Daily_Climate — 3 versions ===

   version      timestamp operation
0        2  1777269217812     WRITE
1        1  1777268191744     WRITE
2        0  1777267464265     WRITE

Details of Last Operation:
{
  "timestamp": 1777269217812,
  "operation": "WRITE",
  "operationParameters": {
    "mode": "Overwrite",
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "predicate": "source_year = 2021"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 3576,
    "num_added_files": 12,
    "num_added_rows": 4151528,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 2
}

=== Gold_Monthly_Climate — 3 versions ===

   version      timestamp operation
0        2  1777269218943     WRITE
1        1  1777268192515     WRITE
2        0  1777267464984     WRITE

Details of Last Operation:
{
  "timestamp": 1777269218943,
  "operation": "WRITE",
  "operationParameters": {
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "mode": "Overwrite",
    "predicate": "source_year = 2021"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 473,
    "num_added_files": 12,
    "num_added_rows": 84061,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "clientVersion": "delta-rs.py-1.5.0",
  "version": 2
}

=== Gold_Station_Metrics — 3 versions ===

   version      timestamp operation
0        2  1777269219876     WRITE
1        1  1777268193174     WRITE
2        0  1777267465648     WRITE

Details of Last Operation:
{
  "timestamp": 1777269219876,
  "operation": "WRITE",
  "operationParameters": {
    "partitionBy": "[\"source_year\",\"source_month\"]",
    "predicate": "source_year = 2021",
    "mode": "Overwrite"
  },
  "engineInfo": "delta-rs:py-1.5.0",
  "clientVersion": "delta-rs.py-1.5.0",
  "operationMetrics": {
    "execution_time_ms": 495,
    "num_added_files": 12,
    "num_added_rows": 84061,
    "num_partitions": 0,
    "num_removed_files": 0
  },
  "version": 2
}

### Bronze Time Travel

We check what the bronze table looked like after the first 5 tables were loaded.

A predicate indicates the file for that predicate was overwritten at that version.

In [15]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Bronze"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 05:22:03
  Predicate : N/A
  Row count : 4,119,205
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 05:33:07
  Predicate : source_year = 2022
  Row count : 8,113,904
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 05:33:11
  Predicate : source_year = 2021
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 05:51:29
  Predicate : source_year = 2021
  Row count : 12,140,454
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("double"), LONGITUDE: PrimitiveType("double"), ELEVATION: PrimitiveType("double"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("double"), TEMP_ATTRIBUTES: PrimitiveType("long"), DEWP: PrimitiveType("double"), DEWP_ATTRIBUTES: PrimitiveType("long"), SLP: PrimitiveType("double"), SLP_ATTRIBUTES: PrimitiveType("long"), STP: PrimitiveType("double"), STP_ATTRIBUTES: PrimitiveType("long"), VISIB: PrimitiveType("double"), VISIB_ATTRIBUTES: PrimitiveType("long"), WDSP: PrimitiveType("double"), WDSP_ATTRIBUTES: PrimitiveType("long"), MXSPD: PrimitiveType("double"), GUST: PrimitiveType("double"), MAX: PrimitiveType("double"), MAX_ATTRIBUTES: PrimitiveType("string"), MIN: PrimitiveType("double"), MIN_ATTRIBUTES: PrimitiveType("string"), PRCP: PrimitiveType("double"), PRCP_ATTRIBUTES: PrimitiveType("string"), SNDP: PrimitiveType("double"), FRSHTT: PrimitiveType("long"), ingested_at: PrimitiveType("timestamp"), source_file: PrimitiveType("string"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte")

DeltaError: Kernel error: Generic delta kernel error: LogSegment end version 3 not the same as the specified end version 4

In production, Ingested At will show the actual month and year ingested since the pipeline will only run once per month

### Silver Time Travel

Check what silver looks like after each transform is done

In [16]:
dt = DeltaTable(layers["Silver"], storage_options=STORAGE_OPTIONS)
history = dt.history()

version_to_info = {
    entry["version"]: {
        "timestamp": pd.to_datetime(entry["timestamp"], unit='ms'),
        "predicate": entry.get("operationParameters", {}).get("predicate", "N/A")
    }
    for entry in history
}

for version in range(0, 5):
    dt_v = DeltaTable(
        layers["Silver"],
        version=version,
        storage_options=STORAGE_OPTIONS
    )
    count = dt_v.to_pyarrow_dataset().count_rows()
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")
    predicate = info["predicate"]
    schema_fields = ", ".join(
        f"{field.name}: {field.type}" 
        for field in dt_v.schema().fields
    )

    print(f"{'─' * 60}")
    print(f"  Version   : {version}")
    print(f"  Ingested  : {ts}")
    print(f"  Predicate : {predicate}")
    print(f"  Row count : {count:,}")
    print(f"  Schema    : {schema_fields}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Version   : 0
  Ingested  : April 27, 2026 05:23:07
  Predicate : N/A
  Row count : 2,077,130
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 1
  Ingested  : April 27, 2026 05:34:47
  Predicate : source_year = 2021
  Row count : 4,152,894
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 2
  Ingested  : April 27, 2026 05:34:47
  Predicate : source_year = 2022
  Row count : 6,238,193
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")
────────────────────────────────────────────────────────────
  Version   : 3
  Ingested  : April 27, 2026 05:52:06
  Predicate : source_year = 2021
  Row count : 6,238,193
  Schema    : STATION: PrimitiveType("string"), DATE: PrimitiveType("date"), LATITUDE: PrimitiveType("float"), LONGITUDE: PrimitiveType("float"), ELEVATION: PrimitiveType("short"), NAME: PrimitiveType("string"), TEMP: PrimitiveType("float"), DEWP: PrimitiveType("float"), SLP: PrimitiveType("float"), STP: PrimitiveType("float"), VISIB: PrimitiveType("float"), WDSP: PrimitiveType("float"), MXSPD: PrimitiveType("float"), GUST: PrimitiveType("float"), MAX: PrimitiveType("float"), MIN: PrimitiveType("float"), PRCP: PrimitiveType("float"), SNDP: PrimitiveType("float"), source_year: PrimitiveType("short"), source_month: PrimitiveType("byte"), source_file: PrimitiveType("string"), ingested_at: PrimitiveType("timestamp"), season_northern: PrimitiveType("string"), day_name: PrimitiveType("string"), is_weekend: PrimitiveType("boolean"), temp_c: PrimitiveType("double"), max_temp_c: PrimitiveType("double"), min_temp_c: PrimitiveType("double"), wdsp_kmh: PrimitiveType("double"), mxspd_kmh: PrimitiveType("double"), gust_kmh: PrimitiveType("double"), is_freezing: PrimitiveType("boolean"), is_extreme_heat: PrimitiveType("boolean"), has_precipitation: PrimitiveType("boolean"), is_gale: PrimitiveType("boolean"), processed_at: PrimitiveType("timestamp")

DeltaError: Kernel error: Generic delta kernel error: LogSegment end version 3 not the same as the specified end version 4

In production this can be done using different months and timestamps for when the transform was executed in airflow

#### Schema Evolution At Bronze Layer

We check to see which columns were removed or added over time

In [ ]:
dt = DeltaTable(layers["Bronze"], storage_options=STORAGE_OPTIONS)

# Build a schema snapshot for each of the first 5 versions
version_schemas = {}
for version in range(0, 5):
    dt_v = DeltaTable(layers["Bronze"], version=version, storage_options=STORAGE_OPTIONS)
    version_schemas[version] = {field.name: str(field.type) for field in dt_v.schema().fields}

# Use version 0 as the baseline
baseline = version_schemas[0]
baseline_cols = set(baseline.keys())

print(f"{'─' * 60}")
print(f"  Baseline schema (version 0) — {len(baseline_cols)} columns")
for name, dtype in baseline.items():
    print(f"    {name}: {dtype}")

for version in range(1, 5):
    current_cols = set(version_schemas[version].keys())
    info = version_to_info[version]
    ts = info["timestamp"].strftime("%B %d, %Y %H:%M:%S")

    added   = current_cols - baseline_cols
    removed = baseline_cols - current_cols
    changed = {
        col for col in current_cols & baseline_cols
        if version_schemas[version][col] != baseline[col]
    }

    print(f"{'─' * 60}")
    print(f"  Version {version} | {ts}")

    if not added and not removed and not changed:
        print(f"    No schema changes from version 0")
    if added:
        for col in added:
            print(f"    + ADDED   {col}: {version_schemas[version][col]}")
    if removed:
        for col in removed:
            print(f"    - REMOVED {col}: {baseline[col]}")
    if changed:
        for col in changed:
            print(f"    ~ CHANGED {col}: {baseline[col]} -> {version_schemas[version][col]}")

print(f"{'─' * 60}")

────────────────────────────────────────────────────────────
  Baseline schema (version 0) — 32 columns
    STATION: PrimitiveType("string")
    DATE: PrimitiveType("date")
    LATITUDE: PrimitiveType("double")
    LONGITUDE: PrimitiveType("double")
    ELEVATION: PrimitiveType("double")
    NAME: PrimitiveType("string")
    TEMP: PrimitiveType("double")
    TEMP_ATTRIBUTES: PrimitiveType("long")
    DEWP: PrimitiveType("double")
    DEWP_ATTRIBUTES: PrimitiveType("long")
    SLP: PrimitiveType("double")
    SLP_ATTRIBUTES: PrimitiveType("long")
    STP: PrimitiveType("double")
    STP_ATTRIBUTES: PrimitiveType("long")
    VISIB: PrimitiveType("double")
    VISIB_ATTRIBUTES: PrimitiveType("long")
    WDSP: PrimitiveType("double")
    WDSP_ATTRIBUTES: PrimitiveType("long")
    MXSPD: PrimitiveType("double")
    GUST: PrimitiveType("double")
    MAX: PrimitiveType("double")
    MAX_ATTRIBUTES: PrimitiveType("string")
    MIN: PrimitiveType("double")
    MIN_ATTRIBUTES: PrimitiveType("string")
    PRCP: PrimitiveType("double")
    PRCP_ATTRIBUTES: PrimitiveType("string")
    SNDP: PrimitiveType("double")
    FRSHTT: PrimitiveType("long")
    ingested_at: PrimitiveType("timestamp")
    source_file: PrimitiveType("string")
    source_year: PrimitiveType("short")
    source_month: PrimitiveType("byte")
────────────────────────────────────────────────────────────
  Version 1 | April 27, 2026 05:34:47
    No schema changes from version 0
────────────────────────────────────────────────────────────
  Version 2 | April 27, 2026 05:34:47
    No schema changes from version 0
────────────────────────────────────────────────────────────